name: scholerxpresse
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  provider: ^5.0.0
    sdk: flutter
  firebase_core: ^2.6.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^5.3.1
  google_sign_in: ^6.0.1
  flutter_facebook_auth: ^6.0.0
  provider: ^6.1.5
  table_calendar: ^3.0.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Example folder for image assets
